// Code generated by protoc-gen-go. DO NOT EDIT.
// source: synchronizationCatatan.proto

/*
Package synchronizationCatatanData is a generated protocol buffer package.

It is generated from these files:
	synchronizationCatatan.proto

It has these top-level messages:
	RequestDataCatatan
	ResponseDataCatatan
	RequestUpdateDataCatatan
	ResponseUpdateDataCatatan
	ServerMyJournalData
	ServerUserData
	ServerCatatanData
	ServerAppSettings
	ServerDetailCatatanData
*/
package synchronizationCatatanData

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestDataCatatan struct {
	IdUser string `protobuf:"bytes,1,opt,name=IdUser" json:"IdUser,omitempty"`
}

func (m *RequestDataCatatan) Reset()                    { *m = RequestDataCatatan{} }
func (m *RequestDataCatatan) String() string            { return proto.CompactTextString(m) }
func (*RequestDataCatatan) ProtoMessage()               {}
func (*RequestDataCatatan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestDataCatatan) GetIdUser() string {
	if m != nil {
		return m.IdUser
	}
	return ""
}

type ResponseDataCatatan struct {
	Data *ServerMyJournalData `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *ResponseDataCatatan) Reset()                    { *m = ResponseDataCatatan{} }
func (m *ResponseDataCatatan) String() string            { return proto.CompactTextString(m) }
func (*ResponseDataCatatan) ProtoMessage()               {}
func (*ResponseDataCatatan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseDataCatatan) GetData() *ServerMyJournalData {
	if m != nil {
		return m.Data
	}
	return nil
}

type RequestUpdateDataCatatan struct {
	Data *ServerMyJournalData `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *RequestUpdateDataCatatan) Reset()                    { *m = RequestUpdateDataCatatan{} }
func (m *RequestUpdateDataCatatan) String() string            { return proto.CompactTextString(m) }
func (*RequestUpdateDataCatatan) ProtoMessage()               {}
func (*RequestUpdateDataCatatan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestUpdateDataCatatan) GetData() *ServerMyJournalData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponseUpdateDataCatatan struct {
	Ok bool `protobuf:"varint,1,opt,name=Ok" json:"Ok,omitempty"`
}

func (m *ResponseUpdateDataCatatan) Reset()                    { *m = ResponseUpdateDataCatatan{} }
func (m *ResponseUpdateDataCatatan) String() string            { return proto.CompactTextString(m) }
func (*ResponseUpdateDataCatatan) ProtoMessage()               {}
func (*ResponseUpdateDataCatatan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResponseUpdateDataCatatan) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ServerMyJournalData struct {
	UserDataObj   *ServerUserData      `protobuf:"bytes,1,opt,name=userDataObj" json:"userDataObj,omitempty"`
	CatatanObjs   []*ServerCatatanData `protobuf:"bytes,2,rep,name=catatanObjs" json:"catatanObjs,omitempty"`
	AppSettingObj *ServerAppSettings   `protobuf:"bytes,3,opt,name=appSettingObj" json:"appSettingObj,omitempty"`
}

func (m *ServerMyJournalData) Reset()                    { *m = ServerMyJournalData{} }
func (m *ServerMyJournalData) String() string            { return proto.CompactTextString(m) }
func (*ServerMyJournalData) ProtoMessage()               {}
func (*ServerMyJournalData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServerMyJournalData) GetUserDataObj() *ServerUserData {
	if m != nil {
		return m.UserDataObj
	}
	return nil
}

func (m *ServerMyJournalData) GetCatatanObjs() []*ServerCatatanData {
	if m != nil {
		return m.CatatanObjs
	}
	return nil
}

func (m *ServerMyJournalData) GetAppSettingObj() *ServerAppSettings {
	if m != nil {
		return m.AppSettingObj
	}
	return nil
}

type ServerUserData struct {
	Id        string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Nama      string `protobuf:"bytes,2,opt,name=Nama" json:"Nama,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=Email" json:"Email,omitempty"`
	NomorTelp string `protobuf:"bytes,4,opt,name=NomorTelp" json:"NomorTelp,omitempty"`
	UrlImage  string `protobuf:"bytes,5,opt,name=UrlImage" json:"UrlImage,omitempty"`
}

func (m *ServerUserData) Reset()                    { *m = ServerUserData{} }
func (m *ServerUserData) String() string            { return proto.CompactTextString(m) }
func (*ServerUserData) ProtoMessage()               {}
func (*ServerUserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServerUserData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServerUserData) GetNama() string {
	if m != nil {
		return m.Nama
	}
	return ""
}

func (m *ServerUserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ServerUserData) GetNomorTelp() string {
	if m != nil {
		return m.NomorTelp
	}
	return ""
}

func (m *ServerUserData) GetUrlImage() string {
	if m != nil {
		return m.UrlImage
	}
	return ""
}

type ServerCatatanData struct {
	KodeBulan int32                      `protobuf:"varint,1,opt,name=KodeBulan" json:"KodeBulan,omitempty"`
	Tahun     int32                      `protobuf:"varint,2,opt,name=Tahun" json:"Tahun,omitempty"`
	Bulan     string                     `protobuf:"bytes,3,opt,name=Bulan" json:"Bulan,omitempty"`
	Detail    []*ServerDetailCatatanData `protobuf:"bytes,4,rep,name=Detail" json:"Detail,omitempty"`
}

func (m *ServerCatatanData) Reset()                    { *m = ServerCatatanData{} }
func (m *ServerCatatanData) String() string            { return proto.CompactTextString(m) }
func (*ServerCatatanData) ProtoMessage()               {}
func (*ServerCatatanData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServerCatatanData) GetKodeBulan() int32 {
	if m != nil {
		return m.KodeBulan
	}
	return 0
}

func (m *ServerCatatanData) GetTahun() int32 {
	if m != nil {
		return m.Tahun
	}
	return 0
}

func (m *ServerCatatanData) GetBulan() string {
	if m != nil {
		return m.Bulan
	}
	return ""
}

func (m *ServerCatatanData) GetDetail() []*ServerDetailCatatanData {
	if m != nil {
		return m.Detail
	}
	return nil
}

type ServerAppSettings struct {
	Lang         string `protobuf:"bytes,1,opt,name=Lang" json:"Lang,omitempty"`
	StatusLoggin string `protobuf:"bytes,2,opt,name=StatusLoggin" json:"StatusLoggin,omitempty"`
}

func (m *ServerAppSettings) Reset()                    { *m = ServerAppSettings{} }
func (m *ServerAppSettings) String() string            { return proto.CompactTextString(m) }
func (*ServerAppSettings) ProtoMessage()               {}
func (*ServerAppSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ServerAppSettings) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *ServerAppSettings) GetStatusLoggin() string {
	if m != nil {
		return m.StatusLoggin
	}
	return ""
}

type ServerDetailCatatanData struct {
	KodeCatatan string `protobuf:"bytes,1,opt,name=KodeCatatan" json:"KodeCatatan,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=Type" json:"Type,omitempty"`
	Tanggal     int32  `protobuf:"varint,3,opt,name=Tanggal" json:"Tanggal,omitempty"`
	Catatan     string `protobuf:"bytes,4,opt,name=Catatan" json:"Catatan,omitempty"`
	JumlahTotal int32  `protobuf:"varint,5,opt,name=JumlahTotal" json:"JumlahTotal,omitempty"`
}

func (m *ServerDetailCatatanData) Reset()                    { *m = ServerDetailCatatanData{} }
func (m *ServerDetailCatatanData) String() string            { return proto.CompactTextString(m) }
func (*ServerDetailCatatanData) ProtoMessage()               {}
func (*ServerDetailCatatanData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ServerDetailCatatanData) GetKodeCatatan() string {
	if m != nil {
		return m.KodeCatatan
	}
	return ""
}

func (m *ServerDetailCatatanData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServerDetailCatatanData) GetTanggal() int32 {
	if m != nil {
		return m.Tanggal
	}
	return 0
}

func (m *ServerDetailCatatanData) GetCatatan() string {
	if m != nil {
		return m.Catatan
	}
	return ""
}

func (m *ServerDetailCatatanData) GetJumlahTotal() int32 {
	if m != nil {
		return m.JumlahTotal
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestDataCatatan)(nil), "synchronizationCatatanData.RequestDataCatatan")
	proto.RegisterType((*ResponseDataCatatan)(nil), "synchronizationCatatanData.ResponseDataCatatan")
	proto.RegisterType((*RequestUpdateDataCatatan)(nil), "synchronizationCatatanData.RequestUpdateDataCatatan")
	proto.RegisterType((*ResponseUpdateDataCatatan)(nil), "synchronizationCatatanData.ResponseUpdateDataCatatan")
	proto.RegisterType((*ServerMyJournalData)(nil), "synchronizationCatatanData.ServerMyJournalData")
	proto.RegisterType((*ServerUserData)(nil), "synchronizationCatatanData.ServerUserData")
	proto.RegisterType((*ServerCatatanData)(nil), "synchronizationCatatanData.ServerCatatanData")
	proto.RegisterType((*ServerAppSettings)(nil), "synchronizationCatatanData.ServerAppSettings")
	proto.RegisterType((*ServerDetailCatatanData)(nil), "synchronizationCatatanData.ServerDetailCatatanData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SynchronizationCatatanService service

type SynchronizationCatatanServiceClient interface {
	DataCatatan(ctx context.Context, in *RequestDataCatatan, opts ...grpc.CallOption) (*ResponseDataCatatan, error)
	UpdateDataCatatan(ctx context.Context, in *RequestUpdateDataCatatan, opts ...grpc.CallOption) (*ResponseUpdateDataCatatan, error)
}

type synchronizationCatatanServiceClient struct {
	cc *grpc.ClientConn
}

func NewSynchronizationCatatanServiceClient(cc *grpc.ClientConn) SynchronizationCatatanServiceClient {
	return &synchronizationCatatanServiceClient{cc}
}

func (c *synchronizationCatatanServiceClient) DataCatatan(ctx context.Context, in *RequestDataCatatan, opts ...grpc.CallOption) (*ResponseDataCatatan, error) {
	out := new(ResponseDataCatatan)
	err := grpc.Invoke(ctx, "/synchronizationCatatanData.synchronizationCatatanService/DataCatatan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synchronizationCatatanServiceClient) UpdateDataCatatan(ctx context.Context, in *RequestUpdateDataCatatan, opts ...grpc.CallOption) (*ResponseUpdateDataCatatan, error) {
	out := new(ResponseUpdateDataCatatan)
	err := grpc.Invoke(ctx, "/synchronizationCatatanData.synchronizationCatatanService/UpdateDataCatatan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SynchronizationCatatanService service

type SynchronizationCatatanServiceServer interface {
	DataCatatan(context.Context, *RequestDataCatatan) (*ResponseDataCatatan, error)
	UpdateDataCatatan(context.Context, *RequestUpdateDataCatatan) (*ResponseUpdateDataCatatan, error)
}

func RegisterSynchronizationCatatanServiceServer(s *grpc.Server, srv SynchronizationCatatanServiceServer) {
	s.RegisterService(&_SynchronizationCatatanService_serviceDesc, srv)
}

func _SynchronizationCatatanService_DataCatatan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDataCatatan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynchronizationCatatanServiceServer).DataCatatan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/synchronizationCatatanData.synchronizationCatatanService/DataCatatan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynchronizationCatatanServiceServer).DataCatatan(ctx, req.(*RequestDataCatatan))
	}
	return interceptor(ctx, in, info, handler)
}

func _SynchronizationCatatanService_UpdateDataCatatan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUpdateDataCatatan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynchronizationCatatanServiceServer).UpdateDataCatatan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/synchronizationCatatanData.synchronizationCatatanService/UpdateDataCatatan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynchronizationCatatanServiceServer).UpdateDataCatatan(ctx, req.(*RequestUpdateDataCatatan))
	}
	return interceptor(ctx, in, info, handler)
}

var _SynchronizationCatatanService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "synchronizationCatatanData.synchronizationCatatanService",
	HandlerType: (*SynchronizationCatatanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataCatatan",
			Handler:    _SynchronizationCatatanService_DataCatatan_Handler,
		},
		{
			MethodName: "UpdateDataCatatan",
			Handler:    _SynchronizationCatatanService_UpdateDataCatatan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "synchronizationCatatan.proto",
}

func init() { proto.RegisterFile("synchronizationCatatan.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0xdd, 0x38, 0xbf, 0x66, 0xfc, 0xa3, 0x52, 0xb7, 0x08, 0x4c, 0x54, 0xa4, 0xc8, 0xa7,
	0x8a, 0x3f, 0xa9, 0x94, 0xc2, 0x07, 0x80, 0x96, 0x43, 0x9a, 0xd0, 0x48, 0x9b, 0xe4, 0xc2, 0x05,
	0x4d, 0x92, 0x95, 0xe3, 0xd6, 0xde, 0x35, 0xf6, 0x1a, 0x29, 0x9c, 0x38, 0x70, 0xe1, 0xca, 0x77,
	0xe0, 0xc2, 0xa7, 0x44, 0xbb, 0x5e, 0xb7, 0x8e, 0x9c, 0x36, 0x39, 0x70, 0xdb, 0x79, 0x33, 0xf3,
	0xe6, 0xed, 0x1b, 0x7b, 0xe1, 0x38, 0x5b, 0xf1, 0xf9, 0x32, 0x15, 0x3c, 0xfc, 0x86, 0x32, 0x14,
	0xfc, 0x1c, 0x25, 0x4a, 0xe4, 0xdd, 0x24, 0x15, 0x52, 0x90, 0xf6, 0xe6, 0xec, 0x05, 0x4a, 0xf4,
	0x5f, 0x01, 0xa1, 0xec, 0x4b, 0xce, 0x32, 0xa9, 0x42, 0x93, 0x21, 0x4f, 0xa0, 0xd9, 0x5f, 0x4c,
	0x33, 0x96, 0x7a, 0x56, 0xc7, 0x3a, 0x69, 0x51, 0x13, 0xf9, 0x9f, 0xe0, 0x88, 0xb2, 0x2c, 0x11,
	0x3c, 0x63, 0xd5, 0xf2, 0x73, 0x68, 0xa8, 0x50, 0x17, 0xbb, 0xbd, 0xd3, 0xee, 0xfd, 0xf3, 0xba,
	0x63, 0x96, 0x7e, 0x65, 0xe9, 0xc7, 0xd5, 0xa5, 0xc8, 0x53, 0x8e, 0x91, 0xc2, 0xa8, 0x6e, 0xf6,
	0x3f, 0x83, 0x67, 0x94, 0x4c, 0x93, 0x05, 0xca, 0x7f, 0x3f, 0xe0, 0x25, 0x3c, 0x2b, 0xc5, 0xd7,
	0x27, 0x1c, 0x80, 0x3d, 0xba, 0xd1, 0xfc, 0xfb, 0xd4, 0x1e, 0xdd, 0xf8, 0x3f, 0x6d, 0x38, 0xda,
	0x40, 0x45, 0x86, 0xe0, 0xe6, 0x19, 0x4b, 0xd5, 0x79, 0x34, 0xbb, 0x36, 0x82, 0x5e, 0x6c, 0x17,
	0x34, 0x35, 0x4d, 0xb4, 0xda, 0x4e, 0x46, 0xe0, 0xce, 0x8b, 0xd2, 0xd1, 0xec, 0x3a, 0xf3, 0xec,
	0xce, 0xde, 0x89, 0xdb, 0x7b, 0xbd, 0x9d, 0xad, 0x82, 0xd0, 0x2a, 0x03, 0x19, 0xc3, 0x23, 0x4c,
	0x92, 0x31, 0x93, 0x32, 0xe4, 0x81, 0x12, 0xb8, 0xa7, 0x05, 0xee, 0x40, 0xf9, 0xee, 0xb6, 0x2d,
	0xa3, 0xeb, 0x1c, 0xfe, 0x0f, 0x0b, 0x0e, 0xd6, 0x6f, 0xa1, 0xec, 0xea, 0x2f, 0xcc, 0xc7, 0x61,
	0xf7, 0x17, 0x84, 0x40, 0xe3, 0x0a, 0x63, 0xf4, 0x6c, 0x8d, 0xe8, 0x33, 0x79, 0x0c, 0xce, 0x87,
	0x18, 0xc3, 0x48, 0x6b, 0x68, 0xd1, 0x22, 0x20, 0xc7, 0xd0, 0xba, 0x12, 0xb1, 0x48, 0x27, 0x2c,
	0x4a, 0xbc, 0x86, 0xce, 0xdc, 0x01, 0xa4, 0x0d, 0xfb, 0xd3, 0x34, 0xea, 0xc7, 0x18, 0x30, 0xcf,
	0xd1, 0xc9, 0xdb, 0xd8, 0xff, 0x63, 0xc1, 0x61, 0xed, 0xfa, 0x8a, 0x6f, 0x20, 0x16, 0xec, 0x7d,
	0x1e, 0x21, 0xd7, 0x82, 0x1c, 0x7a, 0x07, 0x28, 0x0d, 0x13, 0x5c, 0xe6, 0x5c, 0x0b, 0x73, 0x68,
	0x11, 0x28, 0xb4, 0xa8, 0x37, 0xca, 0x8a, 0xda, 0x01, 0x34, 0x2f, 0x98, 0x54, 0x82, 0x1b, 0x7a,
	0x0f, 0x67, 0xdb, 0x4d, 0x2b, 0xea, 0xab, 0xdb, 0x30, 0x14, 0xfe, 0xa0, 0xd4, 0x5a, 0xf1, 0x55,
	0xb9, 0x34, 0x44, 0x1e, 0x18, 0xdf, 0xf4, 0x99, 0xf8, 0xf0, 0xff, 0x58, 0xa2, 0xcc, 0xb3, 0xa1,
	0x08, 0x82, 0x90, 0x1b, 0x07, 0xd7, 0x30, 0xff, 0xb7, 0x05, 0x4f, 0xef, 0x19, 0x48, 0x3a, 0xe0,
	0xaa, 0xeb, 0x1a, 0xc8, 0x50, 0x57, 0x21, 0x35, 0x75, 0xb2, 0x4a, 0x58, 0xb9, 0x1b, 0x75, 0x26,
	0x1e, 0xfc, 0x37, 0x41, 0x1e, 0x04, 0x58, 0x6c, 0xc7, 0xa1, 0x65, 0xa8, 0x32, 0x25, 0x57, 0xb1,
	0x9d, 0x32, 0x54, 0x93, 0x2e, 0xf3, 0x38, 0xc2, 0xe5, 0x44, 0x48, 0x8c, 0xf4, 0x7a, 0x1c, 0x5a,
	0x85, 0x7a, 0xbf, 0x6c, 0x78, 0xbe, 0xd9, 0x33, 0xa5, 0x3e, 0x9c, 0x33, 0xc2, 0xc1, 0xad, 0xfe,
	0x75, 0xdd, 0x87, 0x2c, 0xae, 0xbf, 0x4b, 0xed, 0xd3, 0x87, 0xeb, 0xeb, 0x2f, 0xd3, 0x77, 0x0b,
	0x0e, 0xeb, 0x3f, 0xfb, 0x9b, 0x1d, 0xc6, 0xd6, 0xba, 0xda, 0x6f, 0x77, 0x19, 0x5e, 0x6b, 0x9b,
	0x35, 0xf5, 0x23, 0x7c, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x47, 0x6c, 0xa1, 0x3e, 0xa4, 0x05,
	0x00, 0x00,
}
